### ISSUE TITLE
Not rerender when you change the background to svg-sprite (and can't create two sprites)

### ISSUE THREAD

**Issue by makhnatkin** [JetBrains/svg-sprite-loader#287]
Sorry for my not good English...

**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
I use the SVG sprite in the CSS property background. When classname in a component React change I change background image in the CSS. Due to the fact that the sprite changes the image using the # symbol, redrawing in Chrome does not occur

**Description**
I came up with a solution: to create two sprites: for all the pictures and for hover pictures, then the CSS will change not only #, but also the path. But... I can't create two sprites

```
// main SVG-loader
{
  test: /\.svg$/,
  include: [path.resolve(__dirname, '../src/assets/svg')],
  loader: require.resolve('svg-sprite-loader'),
  options: {
    extract: true,
    spriteFilename: 'static/media/sprite-[hash:6].svg'
  }
},

// hover SVG-loader
{
  test: /\.svg$/,
  include: [path.resolve(__dirname, '../src/assets/svg-hover')],
  loader: require.resolve('svg-sprite-loader'),
  options: {
    extract: true,
    spriteFilename: 'static/media/sprite-hover-[hash:6].svg'
  }
},

```
But works only the first loader, if you change the places of loaders, then in general something strange happens: include is taken from the first, and the options from the second

**Please tell us about your environment:**

- webpack version: 3
- svg-sprite-loader version: 2 

=====
The main thing I want to decide: re-render the background, tell me how. My solution with two sprites is the simplest, but it is impossible to implement

**Comment by makhnatkin** [comment]
@kisenka could you help me?

**Comment by kisenka** [comment]
I need a fully reproducible demo

**Comment by kisenka** [comment]
@makhnatkin could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.
