### ISSUE TITLE
ExtractPluginMissingException

### ISSUE THREAD

**Issue by sultan99** [JetBrains/svg-sprite-loader#297]
I'm trying to use **svg-sprite-loader** in extract mode but I get the error:
```
Module build failed: ExtractPluginMissingException:
svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin
```

**Webpack**
```js
const SpritePlugin = require(`svg-sprite-loader/plugin`)
...
module: {
  rules: [
    {test: /\.(png|jpe?g|woff2?|ttf|eot)$/, loader: `url-loader`},
    {test: /\.svg$/, loader: `svg-sprite-loader`, options: {extract: true}}
  ]
}
plugins: [
  ... ,
  new SpritePlugin()
]
```
As soon as I remove `options: {extract: true}` from rules, it works but I get svg list in my html.
However I want svg list out of my html file.

**Usage**
```js
import appLogo from './app-logo.svg'

const AppLogo = () => (
  <svg>
    <use href={appLogo.url}/>
  </svg>
)
```

**Enviroment**
- Node.js version: 10.4.0
- webpack version: 3.10.0
- svg-sprite-loader version: 3.8.0
- OS type & version: windows 10

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by kisenka** [comment]
@sultan99 ping

**Comment by mistic100** [comment]
I don't know for @sultan99 but I had the problem when linking my build library (NPM module containing the Webpack configuration).

In that case the NAMESPACE constant is `/var/workspaces/application/node_modules/svg-sprite-loader/lib` and the key in the compiler context is `/var/workspaces/common/node_modules/svg-sprite-loader/lib`.

It might be caused by this configuration in my "common" module I used to properly resolve loaders while developping in linked mode.

```
resolveLoader: {
            modules: [
                path.join(config.dir, 'node_modules'), // config.dir == __dirname of the application
                path.join(__dirname, 'node_modules') // __dirname of the common module
            ]
        }
```

**Comment by IUnknown68** [comment]
I have the same problem here, using webpack 4. It appears, webpack changed the structure of some internal data, so the loader can't find the plugin anymore. The point where it fails seems to be https://github.com/kisenka/svg-sprite-loader/blob/af52b750bd91c0bbc6b3be5eaf0afe4817244ec9/lib/loader.js#L49
Hope this helps!

**Comment by adenisovgit** [comment]
Any progress on this issue? I have same problem now. In building prod svg-sprite created, but not connected to index.html. In dev mode - every single svg processing produce same error:
'ExtractPluginMissingException: svg-sprite-loader exception. svg-sprite-loader in extract mode requires the corresponding plugin'

**Comment by sultan99** [comment]
@adenisovgit 
I have resolved the issue, please check it here: https://github.com/sultan99/pizza-order
after running `npm run build`

In public folder you will find `sprite.svg` file which contains all svg (sprites). Check webpack.config and svg plugins. You don't need ramda or cdn plugin.

**Comment by sultan99** [comment]
@kisenka I'm really sorry, I have missed your reply. As I mentioned above, I have resolved it but not sure how far is it in correct way.
