### ISSUE TITLE
Webstorm code assistance broken

### ISSUE THREAD

**Issue by unkernet** [JetBrains/svg-sprite-loader#351]
**Do you want to request a feature, report a bug or ask a question?**
A bug

**What is the current behavior?**
Webstorm code assistance can't analyse webpack.config.js after including `require('svg-sprite-loader/plugin')`; 

**Steps to reproduce:**
- Setup webstorm with webpack integration (see [instructions](https://www.jetbrains.com/help/webstorm/using-webpack.html))
- require svg-sprite-loader/plugin in your webpack.config.js
- you've got an error:
```
Can't analyse webpack.config.js: coding assistance will ignore module resolution rules in this file.
Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE.
Error details:  Cannot read property 'require' of undefined
```
Tested in Webstorm 2018.2 and 2019.2.

**Possible solution:**
```javascript
const webpackVersion = require('webpack/package.json').version;
```
in `lib/utils/get-webpack-version.js`

**Please tell us about your environment:**

- Node.js version: 10.2.1
- webpack version: 3.12.0
- svg-sprite-loader version: 4.1.6
- OS type & version: Ubuntu 16

**Comment by abderrahmane-tj** [comment]
I had to manually change line 9 to `return '4';`for now. a work around, but let's me work :-P

**Comment by unkernet** [comment]
There is no problem here

**Comment by abderrahmane-tj** [comment]
Can we have any sort of response to this issue, or is this repository dead?
