### ISSUE TITLE
Wrong parsing of query params via inline loader

### ISSUE THREAD

**Issue by nbrylevv** [JetBrains/svg-sprite-loader#353]
**Do you want to request a feature, report a bug or ask a question?**
Report a bug.

I use svg-sprite-loader as a inline-loader with replacing symbolId parameter.
```javascript
import '!svg-sprite-loader?symbolId=st-[name]!./../../assets/icons/advanced-search.svg';
// ... other icons
```
And it does't work correctly.

**What is the current behavior?**
I'm debugging `lib/loader.js`:
```javascript
// some code
  /**
   * @type {SVGSpriteLoaderConfig}
   */
  const config = configure(configObj); // this is 45 code line
  console.log(config); // debugging

  if (config.extract) {
    const plugin = parentCompiler
      ? parentCompiler.options.plugins.find(p => p.NAMESPACE && p.NAMESPACE === NAMESPACE)
      : this[NAMESPACE];
// some code
```
And what I get in `config` variable:
```sh
{ '0': '?',
  '1': 's',
  '2': 'y',
  '3': 'm',
  '4': 'b',
  '5': 'o',
  '6': 'l',
  '7': 'I',
  '8': 'd',
  '9': '=',
  '10': 's',
  '11': 't',
  '12': '-',
  '13': '[',
  '14': 'n',
  '15': 'a',
  '16': 'm',
  '17': 'e',
  '18': ']',
  symbolId: '[name]',
  symbolRegExp: '',
  runtimeGenerator:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-sprite-loader/lib/runtime-generator.js',
  runtimeOptions: undefined,
  runtimeCompat: false,
  spriteModule:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-sprite-loader/runtime/browser-sprite.build.js',
  symbolModule:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-baker-runtime/browser-symbol.js',
  esModule: true,
  extract: false,
  spriteFilename: 'sprite.svg' }
```
As you see, my query parameters were parsed wrong.

**What is the expected behavior?**
I expect `symbolId` will have the value I use in query param.
_BTW At the moment I found one solution._
Let's go to `lib/loader.js` again:
```javascript
// some code
  const configObj = { context: loaderContext }; // this is 32 code line

  if (getWebpackVersion.IS_4) {
    configObj.config = matchedRules; // i've changed loaderContext.query to matchedRules
    configObj.target = loaderContext.target;
  } else {
    configObj.config = matchedRules;
    configObj.target = loaderContext.options.target || loaderContext.target;
  }
// some code
```
What I get after changes:
```
{ symbolId: 'st-[name]',
  symbolRegExp: '',
  runtimeGenerator:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-sprite-loader/lib/runtime-generator.js',
  runtimeOptions: undefined,
  runtimeCompat: false,
  spriteModule:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-sprite-loader/runtime/browser-sprite.build.js',
  symbolModule:
   '/Users/nbrylev/Documents/Development/Work/spacetab-vue-components/node_modules/svg-baker-runtime/browser-symbol.js',
  esModule: true,
  extract: false,
  spriteFilename: 'sprite.svg' }
```
That what I need.

**Please tell us about your environment:**

- Node.js version: v10.16.0
- webpack version: v4-ish (I have no idea how to check version of webpack in Storybook)
- svg-sprite-loader version: ^4.1.6
- OS type & version: macOS 10.14.6

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
I'm not sure is it correct way to change `loaderContext.query` to `matchedRules` but it works :)

**Comment by kisenka** [comment]
@nbrylevv still actual? :)

**Comment by nbrylevv** [comment]
@kisenka haven't checked it for a while. I'll try that again this week and message you back

**Comment by nbrylevv** [comment]
@kisenka yep, unfortunately there's same problem

```
"svg-sprite-loader": "^4.2.5"
```

I import icons this way 
```
import '!svg-sprite-loader?symbolId=st-[name]!${iconsImportPath}/{{icon}}.svg';
```
Same result as it was year ago
![Снимок экрана 2020-04-20 в 17 40 19](https://user-images.githubusercontent.com/12825240/79764553-2f171e80-832e-11ea-8cc5-24c17c067ff0.png)

**Comment by nbrylevv** [comment]
Same problem with next import:
```
`import '!svg-sprite-loader?${JSON.stringify({ symbolId: 'st-[name]' })}!${iconsImportPath}/{{icon}}.svg';`
```

Result is
```
{
 '0': '?',
  '1': '{',
  '2': '"',
  '3': 's',
  '4': 'y',
  '5': 'm',
  '6': 'b',
  '7': 'o',
  '8': 'l',
  '9': 'I',
  '10': 'd',
  '11': '"',
  '12': ':',
  '13': '"',
  '14': 's',
  '15': 't',
  '16': '-',
  '17': '[',
  '18': 'n',
  '19': 'a',
  '20': 'm',
  '21': 'e',
  '22': ']',
  '23': '"',
  '24': '}',
  symbolId: '[name]'
// ...
}
```

**Comment by nbrylevv** [comment]
Also I've tried to generate like this (example below) but it was unsuccessful as well:
```
// in generator file
`import '!svg-sprite-loader?"{"symbolId":"st-[name]"}"!${iconsImportPath}/{{icon}}.svg';`

// in generated file
import '!svg-sprite-loader?"{"symbolId":"st-[name]"}"!../../assets/icons/advanced-search.svg';
```

I guess there's mistake in my generating script or something. I'll keep trying to explore it this week.

**Comment by kisenka** [comment]
@nbrylevv it will be much faster if you create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.
