### ISSUE TITLE
Some loaders will be applied after svg-sprite-loader in extract mode

### ISSUE THREAD

**Issue by StijnMaenhaut** [JetBrains/svg-sprite-loader#357]
When using this loader in Webpack Encore, the following error appears:

```
Module Warning (from ./node_modules/svg-sprite-loader/lib/loader.js):
svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode
```

[Reference](https://github.com/kisenka/svg-sprite-loader/blob/af52b750bd91c0bbc6b3be5eaf0afe4817244ec9/lib/loader.js#L56)

Within Webpack Encore, only the priority/order of plugins can be changed, not the priority of loaders. The build succeeds, but keeps throwing this warning on every compile. I searched a lot on this topic, but couldn't find any working solutions (including disabling the images loader).

Can you help me out?

**Comment by infabo** [comment]
This is still a thing in 2020

**Comment by kisenka** [comment]
This happens when some loaders applied after svg-sprite-loader in extract mode.
@StijnMaenhaut @infabo what loaders used in your projects after svg-sprite-loader. If it's inconvenient I can remove this warning.

**Comment by infabo** [comment]
I guess it is the image-webpack-loader thats running after. So the warning is there for a reason. But es @StijnMaenhaut already stated, priority/order of loeads cant be changed in webpack encore. So it may be a thing to fix in encore instead.

**Comment by kisenka** [comment]
So I closing this issue?

**Comment by stijn-maenhaut** [comment]
Yes, you can close the issue. Needs to be fixed in Webpack Encore.

**Comment by StijnMaenhaut** [comment]
Yes, you can close the issue. Needs to be fixed in Webpack Encore.
