### ISSUE TITLE
How to use the BrowserSpriteSymbol type in typescript？

### ISSUE THREAD

**Issue by kaysonwu** [JetBrains/svg-sprite-loader#361]
**Do you want to request a feature, report a bug or ask a question?**

 `question`

**What is the expected behavior?**

```
interface IconProps {
    type: BrowserSpriteSymbol
}
```

**Please tell us about your environment:**

- Node.js version: 10.14.1
- webpack version: last
- svg-sprite-loader version:  last
- OS type & version: Windows 10

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

When I introduced the svg file with `require`, I got a `BrowserSpriteSymbol` type, but I don't know how to use it as a property type. Can you tell me? Thank you!

**Comment by etozhkirill** [comment]
I added next interface in my project
```typescript
interface BrowserSpriteSymbol {
  id: string;
  viewBox: string;
  content: string;
  node: SVGSymbolElement;
}
```

**Comment by kisenka** [comment]
@etozhkirill could you please make a PR with typings?
