### ISSUE TITLE
npm-shrinkwrap needs to be regenerated or removed

### ISSUE THREAD

**Issue by sqal** [JetBrains/svg-sprite-loader#379]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
I recently upgraded this plugin from 4.1.6 to the latest version 4.2.0 and all icons in my app have disappeared. After some digging, I found out that it was caused by some old version of svg-baker, reference issue https://github.com/JetBrains/svg-mixer/issues/2. This dependency was updated in the commit 02d0c33743d98792fc6449791 before releasing 4.2.0 but there are still old dependencies listed in [npm-shrinkwrap.json](https://github.com/JetBrains/svg-sprite-loader/blob/master/npm-shrinkwrap.json#L156).

**What is the expected behavior?**
npm should install correct dependencies.

**Please tell us about your environment:**

- Node.js version: -
- webpack version: -
- svg-sprite-loader version: 4.2.0
- OS type & version: -

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix,**

Remove npm-shrinkwrap (not sure why it is needed since the project using yarn lockfile).

**Comment by kisenka** [comment]
Fixed in `svg-sprite-loader@4.2.1`
