### ISSUE TITLE
require.main.require overwriting causes problems with vscode

### ISSUE THREAD

**Issue by 719media** [JetBrains/svg-sprite-loader#381]
Hello,
I am having a problem where vscode eslint is "crapping out" after including this library.
I get that this is probably a problem with vscode, and not with svg-sprite-loader.

The problem is specifically this line here:
https://github.com/JetBrains/svg-sprite-loader/blob/master/lib/utils/get-webpack-version.js#L6

Which results in the vscode error `Cannot find module webpack/package.json`

Because of this error, eslint effectively "breaks" inside of vscode. If I hardcode `const webpackVersion = 4`, everything works great.

I'm not exactly sure why eslint inside of vscode can't "resolve" this path on installation, but this is my finding so far.

I see that webpack has a version property, but it appears this property was only added since webpack 4, and apparently you support webpack 2-4, so I understand that it is not a solution.

**Comment by xidb** [comment]
Made a PR for that here https://github.com/JetBrains/svg-sprite-loader/pull/382

**Comment by 719media** [comment]
For what it's worth, I still get the error with this PR

**Comment by 719media** [comment]
I have included the PR #382 which also includes a fix for the problem I was having. There may be another way to address this problem, but this is what I went with.

From what I see, this repo treats earlier versions of webpack as default, doing checks like ` if (webpackVersion.IS_4) {` and then having the `else` case correlate to earlier versions of webpack. It may be better to default to webpack 4 (e.g. `if (parseInt(webpackVersion(), 10) >= 3) {` and have the `else` correlate to webpack 4+), but I am not sure of the library author's reasons here. Another reason this would be good is to ensure webpack 5 compatibility, as I imagine this library breaks with webpack 5 currently because of how these checks are written (although I have not tested).

**Comment by xidb** [comment]
> For what it's worth, I still get the error with this PR.

That's right, i updated my PR.

**Comment by 719media** [comment]
OK Cool. To hopefully expedite this, I've closed #383 since it is now a duplicate of #382

**Comment by 719media** [comment]
@kisenka Please consider this issue. There is a PR to fix it. Happy to change it in any way. I'm not sure that the supplied PR #382 fixes it in my preferred way (where the "default" webpack version is treated as 4, instead of null or empty string), but it would be awesome to get something in there so that vscode users using linting get back on latest branch.
Thank you.

**Comment by kisenka** [comment]
Using autodetecting webpack version was very bad idea. I've published alpha version without detecting webpack version, could some of you guys help me with trying it out? 

`npm install svg-sprite-loader@drop-webpack-version-detector`

**Comment by kisenka** [comment]
Detecting webpack version has been dropped in `svg-sprite-loader@4.2.6`
