### ISSUE TITLE
How to use with rollup?

### ISSUE THREAD

**Issue by sayjeyhi** [JetBrains/svg-sprite-loader#393]
Hi there.
First of all thanks to this great work.
I want to use `svg-sprite-loader` in rollup to build my icons pack:

```javascript
import * as react from 'react';
import Symbol from  './index.svg';

const Icon = () =>
   <svg viewBox="${symbol.viewBox}">
       <use xlink:href="#${symbol.id}"></use>
   </svg>;

export default Icon;
```
But this will run in the rollup environment and I will use the es module with webpack. I want to build my icons pack with rollup then sprite them anywhere I use them with webpack. is it possible?

@kisenka

**Comment by kisenka** [comment]
@sayjeyhi this is a loader for **webpack**, not for **rollup**.
