### ISSUE TITLE
wish to support when webpack's  target is 'node-webkit'  for nw.js

### ISSUE THREAD

**Issue by xinhailishi** [JetBrains/svg-sprite-loader#419]
**Do you want to request a feature, report a bug or ask a question?**
report a bug .
**What is the current behavior?**
when use nw,it not works.  it  does not  inject svg to html auto.
**What is the expected behavior?**
wish to support when webpack's  target is 'node-webkit'  for nw.js and inject svg to html.
**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**
svg-sprite-loader-master\lib\configurator.js,
const isTargetBrowser = target => target === 'web' || target === 'electron-renderer';
**Please tell us about your environment:**

- Node.js version: ?
node 12
- webpack version: ?
4.41.1
- svg-sprite-loader version: ? 
4.3
- OS type & version: ?
win 10
**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by xinhailishi** [comment]
i think  it   should  update const isTargetBrowser = target => target === 'web' || target === 'electron-renderer'   to     const isTargetBrowser = target => target === 'web' || target === 'electron-renderer'||'node-webkit'||'nwjs'

**Comment by d3x42** [comment]
PR merged
