### ISSUE TITLE
[DEP_WEBPACK_MODULE_CHUNKS_ITERABLE] DeprecationWarning: Module.chunksIterable: Use new ChunkGraph API

### ISSUE THREAD

**Issue by dmnsgn** [JetBrains/svg-sprite-loader#432]
**Do you want to request a feature, report a bug or ask a question?**

Deprecation warning

**What is the current behavior?**

When running with --trace-deprecation,

```bash
[DEP_WEBPACK_MODULE_CHUNKS_ITERABLE] DeprecationWarning: Module.chunksIterable: Use new ChunkGraph API
    at Function.getChunkGraphForModule (/Users/my-name/Projects/my-project/node_modules/webpack/lib/ChunkGraph.js:1361:10)
    at NormalModule.get chunksIterable [as chunksIterable] (/Users/my-name/Projects/my-project/node_modules/webpack/lib/Module.js:368:21)
    at getModuleChunk (/Users/my-name/Projects/my-project/node_modules/svg-sprite-loader/lib/utils/get-module-chunk.js:11:14)
```

**What is the expected behavior?**

No warning

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: v15.5.1
- webpack version: 5.11.1
- svg-sprite-loader version: 5.2.1
- OS type & version: MacOS 10.15

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by d3x42** [comment]
Please try svg-sprite-loader@6.0.3

**Comment by dmnsgn** [comment]
Warning is gone, functioning as before from initial test 👍 Thanks!
